### PR TITLE
Add Unit Testing For Plugins

### PR DESCRIPTION
**Pull request by suneettipirneni**
Offers unit tests for the plugins by running `npm test` it will give an output of all the failed and passed tests:

This changes `npm test` to run the unit tests instead of the automated test as per convention. Automated integration tests can be run via `npm test:auto`.

Running `npm test` yields:
```
 PASS  src/__tests__/plugin.test.ts
  Plugin Architecture
    ✓ Command to fetch proper plugin (1 ms)
    ✓ Expect plugin to be executed. (1 ms)
    ✓ Plugins with same name to fail (9 ms)

 PASS  src/__tests__/8Ball.test.ts
  8Ball Plugin Tests
    ✓ Replies with message embed (3 ms)

 PASS  src/__tests__/animal.test.ts
  Animal Plugin Tests
    ✓ Fetches Dog Images (410 ms)
```

You can view the full code coverage with the `--coverage` flag:
```
-----------------------------|---------|----------|---------|---------|--------------------------------------
File                         | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                    
-----------------------------|---------|----------|---------|---------|--------------------------------------
All files                    |   20.68 |     4.76 |    9.01 |   21.14 |                                      
 app/handlers                |   14.58 |     0.67 |     3.7 |   14.68 |                                      
  blacklist.handler.ts       |   14.29 |        0 |       0 |   14.29 | 12-63                                
  class_channel.handler.ts   |   33.33 |      100 |       0 |   33.33 | 4-7                                  
  command.handler.ts         |   16.67 |     2.78 |      20 |   16.67 | 14-96,102,117-153                    
  counting.handler.ts        |    9.52 |        0 |       0 |    9.52 | 6-42                                 
  everyone.handler.ts        |   16.67 |        0 |       0 |   16.67 | 6-23                                 
  lionping.handler.ts        |    8.33 |        0 |       0 |    8.33 | 5-26                                 
  membercount.handler.ts     |   17.86 |        0 |       0 |   18.52 | 8-60                                 
  new_member_role.handler.ts |   26.67 |        0 |       0 |   26.67 | 8-32                                 
  persist_roles.handler.ts   |      25 |      100 |       0 |      25 | 5-9                                  
...
```

In addition this PR configures these unit tests to run on each PR:

Screen Shot 2021-07-07 at 7 29 20 PM

### CODE REVIEW

**Review by tanndlin — COMMENTED** [review]
Is it possible to see what the output would look like in discord?
Half of the time, that's what im testing. is to see what h the output looks like

**Comment by tanndlin** [comment]
This is very poggers
What would be the work flow for creating a Test Case for a plugin
And is it possible to specify what the args are in the mock message? like the content

**Comment by suneettipirneni** [comment]
> What would be the work flow for creating a Test Case for a plugin

Yeah, you simply would drop the file in the `__tests__` folder.

> And is it possible to specify what the args are in the mock message? like the content
Yeah you actually can, you'd do something like this:
```ts
const mockMessage = getMessageMock();
mockMessage.content = 'foobar';
```

**Review by c650 — APPROVED** [review]

**Comment by tanndlin** [comment]
Good to merge?

**Comment by suneettipirneni** [comment]
It should be good to merge, other tests can be added later.

**Review by tanndlin — APPROVED** [review]

**Pull request merged**
