### PR TITLE
Fix member count not being stored.

### PR DESCRIPTION
**Pull request by suneettipirneni**
Fixes issue where member count was not being stored.

### CODE REVIEW

**Review by Armintron — APPROVED** [review]
Looks good to me

**Review by c650 — APPROVED** [review]

**Comment by c650** [comment]
should go into develop ?

**Comment by suneettipirneni** [comment]
> should go into develop ?

probably

**Review by tanndlin — CHANGES_REQUESTED** [review]
Did you test this?

**Comment by suneettipirneni** [comment]
> Did you test this?

I don't know how to really test this, because it would require me to have a lot of members in my test server. But I'm pretty sure this fixes the information not being stored properly.

**Comment by c650** [comment]
> I don't know how to really test this,

you can test by lowering the threshhold for logging member record to 1

**Comment by tanndlin** [comment]
> > I don't know how to really test this,
> 
> you can test by lowering the threshhold for logging member record to 1
> 
> or, lower the record in test mongodb cluster to -10000000000, restart bot, should say new record

prob 2 just to make sure its not everytime

**Comment by suneettipirneni** [comment]
I tested this and it seems to be working

**Review by Armintron — APPROVED** [review]

**Comment by tanndlin** [comment]
Should remove the return blocking this from running
https://github.com/cs-discord-at-ucf/lion/blob/dff251357d9d2bba597166abfd7d2b9da63ed128/src/app/handlers/membercount.handler.ts#L12-L14

**Comment by tanndlin** [comment]
Conflicts

**Comment by tanndlin** [comment]
Ohhh, my bad. I told you to remove the `if true return` on the wrong pr. I'll fix it real quick and merge

**Pull request merged**
