### PR TITLE
Added recommended vscode extensions for prettier and eslint

### PR DESCRIPTION
**Pull request by bluffdev**
This will be useful for vscode users that are new to lion.

### CODE REVIEW

**Comment by c650** [comment]
This is fine. Can you point this to our develop branch instead so that I can merge it without triggering a release

**Comment by bluffdev** [comment]
@c650 Can you sync the develop branch with master?

**Comment by tanndlin** [comment]
> @c650 Can you sync the develop branch with master?

The branches are currently even

**Comment by bluffdev** [comment]
I'll have this done in a few months

**Pull request closed without merging**
