### PR TITLE
Change Intervals to use ms 

### PR DESCRIPTION
**Pull request by tanndlin**

### CODE REVIEW

**Comment by Kurtoid** [comment]
My 2c: I like Moment, especially considering it's ubuquity & ease-of-use, but Moment's team itself is discouraging new projects from using it. On the other hand, Moment's intervals are simple enough that there shouldn't be any major overhead

**Comment by suneettipirneni** [comment]
Adding on to that moment.js is being discussed for removal in discord.js

**Review by c650 — APPROVED** [review]

**Comment by c650** [comment]
> Adding on to that moment.js is being discussed for removal in discord.js

in favour of?

**Comment by suneettipirneni** [comment]
> > Adding on to that moment.js is being discussed for removal in discord.js
> 
> in favour of?

Discord.js is [recommending day.js](https://discordjs.guide/miscellaneous/useful-packages.html#moment-js)

**Comment by c650** [comment]
> > > Adding on to that moment.js is being discussed for removal in discord.js
> > 
> > 
> > in favour of?
> 
> Discord.js is [recommending day.js](https://discordjs.guide/miscellaneous/useful-packages.html#moment-js)

@tanndlin what say you

**Comment by tanndlin** [comment]
> > > > Adding on to that moment.js is being discussed for removal in discord.js
> > > 
> > > 
> > > in favour of?
> > 
> > 
> > Discord.js is [recommending day.js](https://discordjs.guide/miscellaneous/useful-packages.html#moment-js)
> 
> @tanndlin what say you

doesn't really affect us
and we dont use it that much. when we do its for readability. so i feel like it doens't really matter what the backend of discordjs is using

**Comment by suneettipirneni** [comment]
> > > > > Adding on to that moment.js is being discussed for removal in discord.js
> 
> > > > 
> 
> > > > 
> 
> > > > in favour of?
> 
> > > 
> 
> > > 
> 
> > > Discord.js is [recommending day.js](https://discordjs.guide/miscellaneous/useful-packages.html#moment-js)
> 
> > 
> 
> > @tanndlin what say you
> 
> 
> 
> doesn't really affect us
> 
> and we dont use it that much. when we do its for readability. so i feel like it doesn't really matter what the backend of discordjs is using

Yes but as stated earlier moment.js is abandoned project that's much larger space-wise than day.js or any other alternative. We should be probably be using day.js or another alternative momentjs suggests.

**Comment by c650** [comment]
> > > > > > Adding on to that moment.js is being discussed for removal in discord.js
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > in favour of?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Discord.js is [recommending day.js](https://discordjs.guide/miscellaneous/useful-packages.html#moment-js)
> > 
> > 
> > > 
> > 
> > 
> > > @tanndlin what say you
> > 
> > 
> > doesn't really affect us
> > and we dont use it that much. when we do its for readability. so i feel like it doesn't really matter what the backend of discordjs is using
> 
> Yes but as stated earlier moment.js is abandoned project that's much larger space-wise than day.js or any other alternative. We should be probably be using day.js or another alternative momentjs suggests.

alright if they, themselves, dont recommend using their lib, then sure we can use day.js. @tanndlin can you do that ?

**Comment by tanndlin** [comment]
Decided to use [ms](https://www.npmjs.com/package/ms). Couldn't quite get what we needed from dayjs without plugins, and `ms`
is exactly what we needed

**Review by suneettipirneni — APPROVED** [review]

**Pull request merged**
