### PR TITLE
Modernize README.md

### PR DESCRIPTION
**Pull request by TheIceCreamBear**
- Added a description to the Lion image for HTML Screenreaders
- Updated Discord server link
- Updated repository GitHub link

(Note: I had intentions to add more to this PR but I am dropping them for now)

### CODE REVIEW

**Comment by tanndlin** [comment]
Sick thanks man!
Since you already have changes in the `README.md` do you mind fixing #639 while ur at it :)

Also you can mark a PR as a draft so we know its still a WIP

**Comment by tanndlin** [comment]
Oh and I pulled the lastest commit from master to develop so you can rebase to remove that extra commit

**Comment by TheIceCreamBear** [comment]
> Sick thanks man! Since you already have changes in the `README.md` do you mind fixing #639 while ur at it :)
> 
> Also you can mark a PR as a draft so we know its still a WIP

For #639 do you mean mention the need for the intents?

**Comment by tanndlin** [comment]
> > Sick thanks man! Since you already have changes in the `README.md` do you mind fixing #639 while ur at it :)
> 
> > 
> 
> > Also you can mark a PR as a draft so we know its still a WIP
> 
> 
> 
> For #639 do you mean mention the need for the intents?

Yeah, you could just include the images, and say to make sure to have those checked

**Comment by TheIceCreamBear** [comment]
I added some language to the read me about creating a bot and ensuring that it has the "Server Members Intent" enabled.

I felt that it wasn't necessary to have them add the guild presence intent as lion does not even specify that intent when logging in.

Also, I have no idea why GitHub is still thinking that it needs to merge the code from Joey, as it is already in develop, and I'm not familiar enough with rebase to try and remove that commit from the list.

**Comment by tanndlin** [comment]
> Also, I have no idea why GitHub is still thinking that it needs to merge the code from Joey, as it is already in develop, and I'm not familiar enough with rebase to try and remove that commit from the list.

Should just be `git rebase origin/develop`

**Comment by tanndlin** [comment]
Is this ready?

**Comment by TheIceCreamBear** [comment]
Yes, this is ready, as this cannot be rebased. (It is not a branch from master on the fork, rather directly on master on the fork.)

**Pull request merged**
