### PR TITLE
Temp remove milestone handler

### PR DESCRIPTION
**Pull request by Armintron**
Spamming the chat

### CODE REVIEW

**Review by c650 — APPROVED** [review]
we dont have a better way ? :pleading_face:

**Comment by suneettipirneni** [comment]
> we dont have a better way ? 🥺

Pretty sure #535 supercedes this

**Comment by c650** [comment]
resolve deepscan by commenting out function body

**Comment by c650** [comment]
> > we dont have a better way ? pleading_face
> 
> Pretty sure #535 supercedes this

lets close this then

**Comment by tanndlin** [comment]
It's [already](https://github.com/cs-discord-at-ucf/lion/commit/815ca558e7e9af4c4cde2e03ba35635a4552bae9) returning automatically on master

**Pull request closed without merging**
