### PR TITLE
Alt Tracking / Logging Initial Implementation

### PR DESCRIPTION
**Pull request by tanndlin**
Only the initial implementation of Alt Tracking

This does not doing anything other than link IDs to each other in the DB, nothing is done with this information as of this PR

### CODE REVIEW

**Comment by tanndlin** [comment]
I don't think you had any issues with these changes, but double check @c650

**Comment by tanndlin** [comment]
@c650 👉 👈

**Review by c650 — COMMENTED** [review]
y no disjoint set

**Comment by tanndlin** [comment]
> y no disjoint set

I'll look into it, just weird cuz of having to store in the DB

Ik how to do it tho 😂

**Pull request merged**
