### PR TITLE
Refactored how C4 got opponent

### PR DESCRIPTION
**Pull request by tanndlin**

### CODE REVIEW

**Review by Armintron — APPROVED** [review]
Looks good to me

**Comment by TylerMathis** [comment]
What is the purpose of this? Does it make the regex mobile/desktop cross compat?

**Comment by tanndlin** [comment]
> What is the purpose of this? Does it make the regex mobile/desktop cross compat?

Creating it as a string, hardcodes the length
Sometimes when someone @'s someone, there is an `!` infront, and sometimes there is not. This guarantees that it get the right ID

**Comment by TylerMathis** [comment]
> > What is the purpose of this? Does it make the regex mobile/desktop cross compat?
> 
> Creating it as a string, hardcodes the length
> Sometimes when someone @'s someone, there is an `!` infront, and sometimes there is not. This guarantees that it get the right ID

Weeeeird, thank you!

**Review by TylerMathis — APPROVED** [review]
<3

**Pull request merged**
